# Generated by Django 4.0.3 on 2022-03-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enderecos',
            new_name='Endereco',
        ),
    ]
